### ISSUE TITLE
Support of hana-defined struct in queries

### ISSUE THREAD

**Issue by joey-xu** [yandex/ozo#115]
Hi, 

I am trying reading a group of columns into one struct.

The example using BOOST_FUSION_DEFINE_STRUCT in the following link works well. 
https://github.com/yandex/ozo/blob/master/docs/howto.md#how-start-to-do-not-bother-with-types-sequence-in-row-but-begin-to-bother-about-column-names

However, when I use BOOST_HANA_DEFINE_STRUCT, it gives the following error message:

In file included from /usr/local/include/boost/hana.hpp:134:
/usr/local/include/boost/hana/map.hpp:479:13: error: static_assert failed due to requirement '!decltype(hana::is_nothing(MaybeIndex{}))::value' "hana::at_key(map, key) requires the
      'key' to be present in the 'map'"
            static_assert(!decltype(hana::is_nothing(MaybeIndex{}))::value,
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/hana/at_key.hpp:51:23: note: in instantiation of function template specialization 'boost::hana::at_key_impl<boost::hana::map_tag, void>::apply<const
      boost::hana::detail::map_impl<boost::hana::detail::hash_table<>, boost::hana::basic_tuple<> > &, boost::hana::type_impl<nibashared::attributes>::_>' requested here
        return AtKey::apply(static_cast<Xs&&>(xs), key);
                      ^
/usr/local/include/boost/hana/detail/operators/searchable.hpp:34:20: note: in instantiation of function template specialization 'boost::hana::at_key_t::operator()<const
      boost::hana::detail::map_impl<boost::hana::detail::hash_table<>, boost::hana::basic_tuple<> > &, boost::hana::type_impl<nibashared::attributes>::_>' requested here
            return hana::at_key(static_cast<Derived const&>(*this),
                   ^

Is BOOST_HANA_DEFINE_STRUCT not supported? Thanks in advance.

**Comment by thed636** [comment]
Hi!

Thanks for asking. 

There is no row reading support for "Boost.Hana"  adapted structures yet. But we can implement it in a couple of days if you really need it. The main problem is what "Boost.Hana" adapted structure is a sequence with read-only access because of "Boost.Hana" algorithms implementation. We made [this workaround](https://github.com/yandex/ozo/blob/master/include/ozo/io/composite.h#L122-L129) which works for user-defined composite types, but it leads to a multiplication of move constructor calls of objects which may cause a performance issue. So if you know a different more optimal solution, please let us know.

So my recommendation is to use "Boost.Fusion" adapted structure for a now until the problem does not solved in "Boost.Hana". But if you really need "Boost.Hana" support in this case - we will implement it.

**Comment by joey-xu** [comment]
Thank you for the timely reply! We are considering using Fusion adapted structure. Another question: is it possible for you to support the read of embedded Fusion struct using Postgres composite type? For example, "SELECT id, name, (a, b, c)::composite_type_name FROM xxx", and directly put the (id, name, (a, b, c)) into an embedded Fusion struct?

**Comment by fyt000** [comment]
Not sure if I am understanding "read-only" sequence access correctly, but how about something like this?
```
    boost::hana::for_each(boost::hana::keys(t), [&t](auto key) {
        auto &member = boost::hana::at_key(t, key);
        // do whatever
        // member = 123;
    });
```

**Comment by thed636** [comment]
> Not sure if I am understanding "read-only" sequence access correctly, but how about something like this?
> 
> ```
>     boost::hana::for_each(boost::hana::keys(t), [&t](auto key) {
>         auto &member = boost::hana::at_key(t, key);
>         // do whatever
>         // member = 123;
>     });
> ```

Yes, this works great! We failed to use `boost::hana::members`, and completely missed the sight of using of `boost::hana::keys`.
Thanks a lot for the advice! The fix is on the way!

**Comment by thed636** [comment]
> Thank you for the timely reply! We are considering using Fusion adapted structure. Another question: is it possible for you to support the read of embedded Fusion struct using Postgres composite type? For example, "SELECT id, name, (a, b, c)::composite_type_name FROM xxx", and directly put the (id, name, (a, b, c)) into an embedded Fusion struct?

Well, first of all you need to use [OZO_PG_DEFINE_CUSTOM_TYPE](https://yandex.github.io/ozo/group__group-type__system-mapping.html#gaab97efce284cc18ac78a761f840edde1) macro to define your structure as a composite type in database. 
Next step is to say what you want to use this type via [ozo::register_types()](https://yandex.github.io/ozo/group__group-type__system-functions.html#gac97d30cda822b83aa3d54f60c658f8f7). Use this function return value as an OidMap argument of connection source [connection_info](https://yandex.github.io/ozo/group__group-connection-functions.html#ga7edf7162c365d85de16c9b34659140af).
Please have a look at [this composite declarations](https://github.com/yandex/ozo/blob/master/tests/integration/request_integration.cpp#L71-L77) and [this test](https://github.com/yandex/ozo/blob/master/tests/integration/request_integration.cpp#L258-L295) as an example of composite type receiving.

In your case (skipping the structure adaptation code and other non-significant details) it might be something like this:

```c++
struct my_composite_type {
    <type of a> a,
    <type of b> b,
    <type of c> c
};

OZO_PG_DEFINE_CUSTOM_TYPE(my_composite_type, "composite_type_name");

struct my_adapted_row {
    <your type of id> id,
    std::string name,
    my_composite_type composite
}; 

// ..
const auto conn_info = ozo::make_connection_info(
           "host=... port=... dbname=...",
            ozo::register_types< my_composite_type >());

ozo::rows_of<my_adapted_row> out;
ozo::request(ozo::make_connector(conn_info, io),
             "SELECT id, name, (a, b, c)::composite_type_name as composite FROM xxx"_SQL,
            ozo::into(out), yield);
// ...
```
PS: thanks to @three0s , the ["Hana-adapted structure as a row"](https://github.com/yandex/ozo/tree/fix_hana_adapted_composite) is on the way.

**Comment by joey-xu** [comment]
Thanks. It is working now. Awesome!
