### ISSUE TITLE
Boost 1.65 support?

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#140]
Is it at all possible to support Boost 1.65? My Linux distribution does not supply 1.66 at this time.

**Comment by thed636** [comment]
Hi Michael! Thanks for the request. Unfortunately, the short answer is no. :(

The long story is - before Boost 1.66 version, there is no Networking TS compatible interface in Asio. In the beginning, we tried to support both old and Networking TS compatible interfaces. But this is a very error-prone way (e.g. old interface strand class and new interface strand executor are two different and incompatible things). So the best choice for you is to move to a newer version of Boost and Networking TS compatible interfaces. And the only solution in your case - build Boost from its sources. Hope that helps.

**Comment by jonesmz** [comment]
Ok. Thanks for the explanation. I appreciate it.
