### ISSUE TITLE
Wrong link in README

### ISSUE THREAD

**Issue by alexander-ivanov** [yandex/ozo#163]
Link from "learn more about main use-cases from unit tests," - "https://github.com/yandex/ozo/blob/master/tests/request_integration.cpp" is broken. Should be "https://github.com/yandex/ozo/blob/master/tests/integration/request_integration.cpp"

**Comment by thed636** [comment]
Hi, Alexander!

Thanks for the issue!

**Comment by koshachy** [comment]
Fixed!
