### ISSUE TITLE
macro name is a reserved identifier

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#177]
```
/home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/error.h:527: warning: macro name is a reserved identifier [-Wreserved-id-macro]
        #define __OZO_SQLSTATE_NAME(value) case value: return std::string(#value) + "(" + detail::ltob36(value) + ")";
                ^
```

**Comment by thed636** [comment]
Hi Michael!

Nice to see you again! Thanks for the issue. There are two things I have to say about this.

First of all, it would be nice to have additional information about the platform and the compiler. Such information is really helpful for understanding the issue and its severity. So if you want to be heard, please do not hesitate to talk. 

Second - PR is always welcome, and the previous one from you was very helpful. So if you do not want to bother with a lengthy description of the problem (how to reproduce it and so on) - the PR with a brief commit message is the best choice then.

With best regards,
Sergei

**Comment by jonesmz** [comment]
> Nice to see you again!

I'm now able to use Boost 1.67, so I'm working on adopting OZO, replacing libpqxx.

> First of all, it would be nice to have additional information about the platform and the compiler.

https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

> 17.4.3.1.2 Global names [lib.global.names]
> Certain sets of names and function signatures are always reserved to the implementation:
> 
> Each name that contains a double underscore (__) or begins with an underscore followed by an uppercase letter (2.11) is reserved to the implementation for any use.
>
> Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.(*)
>
> * Such names are also reserved in namespace ::std (17.4.3.1).

Identifiers with double underscore are reserved to the exclusive use of the compiler and standard library vendor. The use of two underscores in this macro in OZO is undefined behavior.

In this case, I was using Clang 8, on a Linux distribution, when I got the warning. You may need to turn on -Wextra to trigger it.

**Comment by thed636** [comment]
Now I see. Thanks for the report. The problem is not critical but I think we can easily fix it in one of the upcoming PRs.
