### ISSUE TITLE
Implicit conversion loses integer precision

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#187]
```cpp
template <typename T>
inline Require<Integral<T> && sizeof(T) == 1, istream&> read(istream& in, T& out) {
    out = in.get();
    if (!in) {
        throw system_error(error::unexpected_eof);
    }
    return in;
}
```

> ozo/include/ozo/impl/read.h:26: warning: implicit conversion loses integer precision: 'std::basic_istream<char, std::char_traits<char> >::int_type' (aka 'int') to 'char' [-Wimplicit-int-conversion]
>     out = in.get();
>         ~ ~~~^~~~~

> ozo/include/ozo/impl/read.h:51: in instantiation of function template specialization 'ozo::impl::read<char>' requested here
>     read(in, tmp);
>     ^

My suggestion is to use `boost::numeric_cast`

**Comment by thed636** [comment]
Well, IMO `static_cast<T>` should be enough here since this is a standard input stream interface and we know the size of T is one byte.

**Comment by jonesmz** [comment]
Looking further into it, there's apparently a set of functions intended to be used for this.

https://stackoverflow.com/questions/24482728/return-value-of-istreamget

**Comment by thed636** [comment]
~Yep, `traits_type::to_char_type(c)` is good solution!~

Looks like method `get` with out-parameter is the best solution at the moment.

The stream interfaces are just endless... :)
