### ISSUE TITLE
Replace BOOST_FUSION_ADAPT_STRUCT with BOOST_HANA_ADAPT_STRUCT in examples

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#203]
Since ozo already explicitly depends on Boost.Hana, I think it makes sense to provide examples for adapting structs that use Boost.Hana instead of Boost.Fusion.

My motivation behind recommending this is actually that I ran into a problem including BOOST_FUSION_ADAPT_STRUCT in the same translation unit as a Boost.MultiIndex container. It causes a compiler error, no idea why. However, BOOST_HANA_ADAPT_STRUCT doesn't have the same problem.

**Comment by thed636** [comment]
Hi Michael!

Could you provide additional information about of problem do you have? We are using both Boost.Fusion and Boost.MultiIndex in many translation units and have no problem.

**Comment by jonesmz** [comment]
See this discussion for more information: https://github.com/redboltz/mqtt_cpp/issues/351

*Appears* to be the same problem that I had when I opened this issue, but the error messages were different, and given C++'s errors tend to be unworkable / unreadable  sometimes, I just didn't try to track down the underlying issue.

Using BOOST_HANA_ADAPT_STRUCT instead of BOOST_FUSION_ADAPT_STRUCT allowed me to compile OZO into my application.

**Comment by thed636** [comment]
Hi, Michael! 

Thanks a lot for the information! I think, first of all, I'll add some references for this problem into the documentation. According to examples - I think at least one of them should use Boost.Fusion just for the display purpose.

**Comment by thed636** [comment]
Documentation and examples are updated.
