### ISSUE TITLE
Request for explanation how to use OZO_PG_BIND_TYPE with timestamptz

### ISSUE THREAD

**Issue by enricodetoma** [yandex/ozo#204]
I'm using the ICU library for managing timestamps.

The timestamps are composed of:

- milliseconds from 1970-Jan-01 UTC represented as `double`
- a timezone http://userguide.icu-project.org/datetime/timezone

Which is the best way to map it to a `timestamptz` with `OZO_PG_BIND_TYPE`?

Should I simply format my timestamps to ISO8601 strings like `YYYY-MM-DDThh:mm:ss.sTZD` (eg `1997-07-16T19:20:30.45+01:00`) and then bind them as strings?

Or can I write C++ mapping code to map my timestamps to 8 bytes binary representation of timestamptz? And if yes, how is a `timestamptz` represented in binary form?

I'm mainly interested in one way binding (ICU timestamps => Postgresql) for INSERTs and UPDATEs and for use in WHERE clauses, not the other way as SELECT results.

**Comment by thed636** [comment]
Hi!

That's a good question!

> I'm using the ICU library for managing timestamps.
>
> The timestamps are composed of:
>
> * milliseconds from 1970-Jan-01 UTC represented as double
> * a timezone http://userguide.icu-project.org/datetime/timezone
>
> Which is the best way to map it to a timestamptz with OZO_PG_BIND_TYPE?
>
> Should I simply format my timestamps to ISO8601 strings like YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00) and then bind them as strings?

Well, if you do not want to bother with an adaptation of your `timestamptz` representation type and this is not a part of another composite type, you can simply pass the string representation and then explicitly cast the parameter to `timestamptz` inside a query text. E.g.:

```c++
const auto query = "select * from table where time < "_SQL + to_string(t) + "::timespamtz";
```

> Or can I write C++ mapping code to map my timestamps to 8 bytes binary representation of timestamptz? And if yes, how is a timestamptz represented in binary form?

Yes, of course. In the binary protocol, `timestamptz` transfer is literally the same as `timestamp` except the value should be presented in the UTC time-zone (no timezone information is stored in PostgreSQL). So you can look at PR #155 for the details. You can do the same inside your project. 

> I'm mainly interested in one way binding (ICU timestamps => Postgresql) for INSERTs and UPDATEs and for use in WHERE clauses, not the other way as SELECT results.

In the summary:

* if **the timestamp appears in a query as a simple parameter** IMO the best choice may be to use string (`text`) representation and then explicit cast to `timestamptz` in a query, the only disadvantage here is the database-side typecast but it should not be a problem; 
* if **the timestamp is a part of some composite** it is better to use the type adaptation to avoid boilerplate code around converting the field of a composite as on the C++ side so on SQL side.

I hope that helps. If you have any questions, please do not hesitate to ask.

Best regards,
Sergei

**Comment by enricodetoma** [comment]
Thank you, very informative! I think we can close this issue.
