### ISSUE TITLE
CMake Error: `resource_pool` is missing.

### ISSUE THREAD

**Issue by ricejasonf** [yandex/ozo#215]
```
CMake Error at contrib/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /usr/local/src/ozo-4bf9f42098cead27d4a3d4c1af2d06eb360f24cb/contrib/resource_pool

  does not contain a CMakeLists.txt file.
```

This happens when building from an archive of the source code (ie without git).

This is a bit of a speed bump for people trying use this library for the first time. Perhaps documenting `resource_pool` as a dependency would be useful.

Is it a required dependency?

**Comment by thed636** [comment]
Hi, Jason!

Yes, `resource_pool` is required, and you're right, it should be documented. Thanks for the report!
