### ISSUE TITLE
Clang 9, lots of warnings about non-static variables in headers.

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#220]
Long story short: Ozo has lots of template variables declared in header files where the value of the variable is the result of a type_traits's evaluation.

E.g.:

```
template <typename T>
constexpr auto OutputIterator = is_output_iterator<T>::value;
```

Clang is warning about this because a globally defined variable like this should either have an "extern" declaration before it, or be static. Otherwise from the compiler's perspective, you risk violating the one-definition-rule.

Replacing these template-variables with "using" declarations will resolve the complaint from clang.

Full text of warning follows.

> In file included from /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/connection_info.h:3:
> In file included from /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/connector.h:4:
> In file included from /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/connection.h:8:
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:28:16: warning: no previous extern declaration for non-static variable 'IsNone<std::chrono::duration<long, std::ratio<1, 1000000000> > >' [-Wmissing-variable-declarations]
> constexpr auto IsNone = is_none<T>::value;
>                ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:33:43: note: in instantiation of variable template specialization 'ozo::IsNone' requested here
> template <typename T, typename = Require<!IsNone<T>>>
>                                           ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:34:23: note: in instantiation of default argument for 'operator==<std::chrono::duration<long, std::ratio<1, 1000000000> > >' required here
> inline constexpr bool operator == (const T&, const none_t&) { return false;}
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/deadline.h:107:30: note: while substituting deduced template arguments into function template 'operator==' [with T = std::chrono::duration<long, std::ratio<1, 1000000000> >, $1 = (no value)]
>     return time_left(t, now) == time_traits::duration(0);
>                              ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:28:11: note: declare 'static' if the variable is not intended to be used outside of this translation unit
> constexpr auto IsNone = is_none<T>::value;
>           ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:28:16: warning: no previous extern declaration for non-static variable 'IsNone<ozo::detail::endian>' [-Wmissing-variable-declarations]
> constexpr auto IsNone = is_none<T>::value;
>                ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:33:43: note: in instantiation of variable template specialization 'ozo::IsNone' requested here
> template <typename T, typename = Require<!IsNone<T>>>
>                                           ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:34:23: note: in instantiation of default argument for 'operator==<ozo::detail::endian>' required here
> inline constexpr bool operator == (const T&, const none_t&) { return false;}
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/detail/endian.h:27:34: note: while substituting deduced template arguments into function template 'operator==' [with T = ozo::detail::endian, $1 = (no value)]
> constexpr Require<endian::native == endian::little, U> convert_to_big_endian(T value) noexcept {
>                                  ^
> /home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/core/none.h:28:11: note: declare 'static' if the variable is not intended to be used outside of this translation unit
> constexpr auto IsNone = is_none<T>::value;
>           ^

**Comment by thed636** [comment]
Michael, thanks for the report!

I think the problem is on the Clang side. Correct me if I'm wrong, but constexpr variables should be inline by default. Try to add `inline` before the `constexpr` the warning should disappear.

**Comment by jonesmz** [comment]
Correction.

The "using" keyword won't help with this.

The "inline" keyword is the fix.
