### ISSUE TITLE
Does ozo provide a cursor to not fetch all data at once?

### ISSUE THREAD

**Issue by nobleread** [yandex/ozo#230]
Hello,

maybe it's a silly question, but I couldn't find an answer for it reading the docs. So is it possible to execute a query and fetch results row by row, instead of fetching everything at once, for example in case a response contains tons of data?
I saw an implementation of this concept (fetch & cursor) on 'ideas' branch, but this was never merged into master. It was also mentioned on boostcon/cppnow presentation.

**Comment by thed636** [comment]
Hi!

The short answer - unfortunately, OZO does not support single-row mode yet. 

The little longer story is that we found the single-row mode is not very efficient, so we decided to implement this feature later. As an alternative, you can use the [CURSOR](https://www.postgresql.org/docs/12/plpgsql-cursors.html) mechanism to read the result by chunks. In that case, you can manage the size of the data chunk and receive data more efficiently. 

Another option is using [COPY](https://www.postgresql.org/docs/12/sql-copy.html) command, but it requires [PQgetCopyData](https://www.postgresql.org/docs/12/libpq-copy.html) support in the library, seems like not a big problem to add (much easier than single-row mode), but requires some code and tests.

**Comment by nobleread** [comment]
Thank you for your answer. It seems like `ozo` doesn't prefetch any records when using cursors, and in case I write a statement to fetch 1 record 100 times, it will go to the database 100 times for 1 record, right? It treats cursors like any other raw SQL and just sends it to database. Did single-row mode support prefetching?

**Comment by thed636** [comment]
> It seems like ozo doesn't prefetch any records when using cursors, and in case I write a statement to fetch 1 record 100 times, it will go to the database 100 times for 1 record, right? 

If you call `ozo::request` 100 times requesting one row in a query - yes, if you requesting 100 records in a single query - no. So it depends on what you want.

> Did single-row mode support prefetching?

Single row mode is for fetching result row-by-row.

**Comment by nobleread** [comment]
OK, clear, thank you for explanation.

**Comment by thed636** [comment]
No more activity here so I close the issue. Feel free to reopen if needed.
