### ISSUE TITLE
Refreshing connection in connection_pool

### ISSUE THREAD

**Issue by nobleread** [yandex/ozo#243]
Currently, I cannot see any option to configure connection_pool to refresh connection. The functionality I'm referring to is explained e.g. [here](https://docs.oracle.com/cd/B28359_01/java.111/e10788/manage.htm#BABDDFJG). Only the `idle_timeout` option is available, but I can imagine a scenario, where e.g. 1 out of 4 connections is used constantly for over 24h, which may result in some issues.
Is this refresh functionality somehow achievable in ozo? Or do you think it will be added in future?

**Comment by thed636** [comment]
Hi!

> I can imagine a scenario, where e.g. 1 out of 4 connections is used constantly for over 24h, which may result in some issues.

What kind of issues do you mean?

> Is this refresh functionality somehow achievable in ozo? 

E.g. you may extend ozo functionality by writing a wrapper for the `ozo::connection_pool` and do all the things there.

> Or do you think it will be added in future?

We don't have such a feature in plans, but you can make a PR. This is not rocket science. :) I will help you to implement such functionality in the best way for the library.

With best regards,
Sergei

**Comment by elsid** [comment]
I think this specific feature (maximum lifetime of a connection) can be implemented in [resource_pool](https://github.com/elsid/resource_pool/blob/bc3d08283fc03d99221e33aa4f868fb69be208cd/include/yamail/resource_pool/detail/storage.hpp#L115).

**Comment by elsid** [comment]
Here is resource lifespan feature: https://github.com/elsid/resource_pool/pull/23. After this pr is merged few changes are required for ozo.

Next step is to think about pool refresh:
> Refreshing a connection pool replaces every connection in the pool with a new connection. Any connections that are currently borrowed are marked for removal and refreshed after the connection is returned to the pool.

**Comment by nobleread** [comment]
Hello Sergei,

sorry for such delayed response. As to the issues with long lasting connection, I can think of couple of things that can go wrong, e.g.:
- "temporary tables cannot be accessed by autovacuum. Therefore, appropriate vacuum and analyze operations should be performed via session SQL commands" [(source)](https://www.postgresql.org/docs/12/routine-vacuuming.html#VACUUM-FOR-WRAPAROUND) and other postgresql-specific issues,
- "allowing connection pool to gracefully recover when the database server has been restarted, and all previously established connections are no longer functional" [(source)](https://docs.sqlalchemy.org/en/13/core/pooling.html) and other, more general, problems.

> I think this specific feature (maximum lifetime of a connection) can be implemented in resource_pool.

I was not sure whether to place a question for this functionality here or there, sorry.

**Comment by thed636** [comment]
> "temporary tables cannot be accessed by autovacuum. Therefore, appropriate vacuum and analyze operations should be performed via session SQL commands" (source) and other postgresql-specific issues,

AFAIK this is a problem only if there is a transaction opened within a connection, not a problem for an idle connection. `ozo::connection_pool` holds only idle connections, all the connections with state differing from idle are closed on return. Thus no connection pool option may help here. This should be solved by an application.

> "allowing connection pool to gracefully recover when the database server has been restarted, and all previously established connections are no longer functional" (source) and other, more general, problems.

`idle_timeout` indeed option is responsible for such a case. If a connection spends more than `idle_timeout` inside the pool it becomes outdated and will be reopened on poping from the pool.

**Comment by elsid** [comment]
https://github.com/elsid/resource_pool/pull/24 adds a support for explicit refresh method.
