### ISSUE TITLE
Thoughts about https://github.com/hotkit/pgasio

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#244]
I'm curious about the project maintainers of OZO's thoughts regarding the pgasio library.

It's a from-scratch implementation of the postgresql wire protocol.

I know that OZO uses libpq, from Postgresql, directly.

I don't have any specific suggestions or concerns about it, and I'm not trying to imply that OZO should consume pgasio instead of libpq. Really just looking for any first impressions and that's all.

**Comment by thed636** [comment]
Hi Michael!

Thanks for the link! We thought about custom implementation of the protocol on the very beginning stage of the project but decided to do no move in that way. Supporting custom implementation of a protocol especially without detailed documentation (I mean flow charts) is hard. So we decided to concentrate our resources on the things we need atop of native protocol implementation like introspection support, type safety, connection pooling and failover. I can’t say that libpq is a convenient solution for asynchronous software, but the custom implementation will consume much more resources than using libpq.
