### ISSUE TITLE
Borrowing connection from ozo::connection_pool

### ISSUE THREAD

**Issue by nobleread** [yandex/ozo#252]
Hello,

is it possible to 'borrow' a connection from `ozo::connection_pool`? What I mean by 'borrowing' is this: lets say I have an `ozo::connection_pool` configured for 4 connections. Now I would like to take 1 connection outside and use it however I want to, so that `connection_pool` could operate only on remaining 3 connections. In the end I would return borrowed connection, so the `connection_pool` would have 4 connections again. I couldn't find such functionality by browsing documentation/src/tests, but maybe it exists already and I've missed it. I also know that I could have a separate connection besides connection pool, but I'm interested in keeping fixed number of connections opened.

**Comment by thed636** [comment]
Hi!

To be honest I do not understand the question - this is how the connection pool works. You can get the connection as a result of the first request or directly via `ozo::get_connection()` and use it in any way. The connection will return to the pool at the destruction.

Does it make sense?

**Comment by nobleread** [comment]
Yes it does, didn't know it works this way. Thank you very much for explanation!

**Comment by thed636** [comment]
You are welcome!
