### ISSUE TITLE
SEGFAULT when committing transaction twice

### ISSUE THREAD

**Issue by nobleread** [yandex/ozo#253]
Hello,

I've just noticed, that when invoking `ozo::commit(transaction, yield)` twice on 1 transaction, instead of error being thrown, segmentation fault occurs (possibly due to invalid check for `empty()`, which refers to deallocated memory). You can check stack trace here: https://gist.github.com/nobleread/3831163af471d2ffdc20b033778d4477

**Comment by thed636** [comment]
Hi.

I think to make `ozo::commit` twice leads to UB. Since the transaction frees connection on the first commit operation. Could you please to describe that are you trying to do doing two commits?

**Comment by nobleread** [comment]
I thought performing commit/rollback on a moved-from transaction object should fail with some exception being thrown and only tested for throwing such exception, but was surprised to find out it actually fails with SEGFAULT, hence my post. If it's meant to stay UB, then nevermind.

**Comment by thed636** [comment]
Use of object after `std::move` applied is a UB for C++. Providing throwing exception logic for this case costs additional code with logic to support it. Since in the standard this is UB I do not see a good reason for such logic. But it looks like this behaviour should be documented. Thanks for the report.

**Comment by nobleread** [comment]
Does it also mean, that I cannot call `operator bool()` or `has_connection()` on a moved-from transaction? Is there any other way to know if I can still use it?

**Comment by thed636** [comment]
Well, actually it will be UB too. There are a lot of debates that the object should be in some null-state after being moved, but still, no single opinion exits. So, the best way, if you want to re-use the object is to reset it into null-state, e.g. using the default constructed one.

E.g.:

```c++
transaction = decltype(transaction){};
```

or:

```c++
decltype(transaction) tmp;
std::swap(transaction, tmp);
ozo::commit(std::move(tmp), yield);
```

In this case, the `transaction` object will be in the null state and no UB should be.

**Comment by nobleread** [comment]
Got it, thanks!

**Comment by thed636** [comment]
#218 - the refactored transaction should contain the necessary documentation notes
