### ISSUE TITLE
ozo::literals operator+() not overloaded

### ISSUE THREAD

**Issue by neel** [yandex/ozo#271]
I am trying to generate SQL query at compile time
```
auto comma() {
    using namespace ozo::literals;
    return ", "_SQL;
}
auto a() {
    using namespace ozo::literals;
    return "a"_SQL;
}
auto b() {
    using namespace ozo::literals;
    return "b"_SQL;
}
template <typename LeftT, typename RightT>
auto both(LeftT l, RightT r) {
    return l + comma() + r;
}
```
Then I am trying to use `both` while creating the sql query

```
const auto sql = "select "_SQL + both(a(), b()) + " from X"_SQL;
```

`error: no match for ‘operator+’ (operand types are ‘ozo::query_builder<boost::hana::tuple<ozo::query_element<boost::hana::string<'a'>, ozo::query_text_tag> > >’ and ‘ozo::query_builder<boost::hana::tuple<ozo::query_element<boost::hana::string<',', ' '>, ozo::query_text_tag> > >’)`

**Comment by neel** [comment]
Aha!! I need `std::move`. But why so ? `boost::hana::string` doesn't need to be moved in order to be concatenated.

**Comment by thed636** [comment]
Hi Neel.

Well, the query builder may contain not text parts only, it contains query parameters as well. This approach prevents a hidden copying of parameters. 

And the alternative approach is to construct text by any of string representations and use [ozo::make_query](https://yandex.github.io/ozo/group__group-query-functions.html#ga109e1bd312a3e4674b9bf2e299d55de5) function that may fit better to your application. 

Hope that help.
