### ISSUE TITLE
ozo for other SQL databases

### ISSUE THREAD

**Issue by neel** [yandex/ozo#276]
Is there any plan on developing ozo backends for other SQL databases like mysql, SQL Server, Oracle etc.. ?

**Comment by thed636** [comment]
Hi, Neel!

That's a good question. The short answer - unfortunately, no. 

Here is a slightly longer answer.
OZO was designed as a PostgreSQL client library for C++17. Thus it is tightly bound for the PostgreSQL protocol and type system. There is no database abstraction layer is similar to one of ORM. So it may not be easily adapted for a different DBMS. But the ideas and approach may be applied to a different project that is aimed to be a universal client for different DBMS. For now, we have no such plans, but who knows, maybe it is a good idea to try creating such a project for C++20.

With best regards.
