### ISSUE TITLE
 I get the error Connection timeout at normal load.

### ISSUE THREAD

**Issue by AntonMamedov** [yandex/ozo#301]
I get the error Connection timeout and get resource timeout at normal load. In connection_pool_config, I set the capacity to 100, and the queue_capacity to an unrealistic 100,000,000, but despite this, I still get an error message on a fairly small load. All requests are performed with the ozo :: none parameter. How to fix it?

I tried to set the timeout to 100s, it didn't help. Error codes 110, 1

**Comment by AntonMamedov** [comment]
According to my observations, the problem does not always occur, but at least half the time. In the same load tests, the error can take off or not. At the same time, on the number of connections more than 10, it always crashes.

**Comment by thed636** [comment]
Hi Anton,
Could you please provide a code example to reproduce the problem?

**Comment by thed636** [comment]
Since there is no example to reproduce, I closed the issue. Please feel free to reopen it with new information or steps to reproduce the problem.
