### ISSUE TITLE
How can I include this library?

### ISSUE THREAD

**Issue by systocrat** [yandex/ozo#307]
Hello!

I'd like to make ozo available to my own CMake project.

It may seem foolish, but I need some help. What would be the easiest way to do this? Since they are both header-only, I attempted to vendor both ozo and resource_pool via git submodule, but I'm not so experienced with CMake that I could make it work.

Could you offer any guidance here?

**Comment by thed636** [comment]
Hi!

You can look at [tests/external_project/CMakeLists.txt](https://github.com/yandex/ozo/blob/master/tests/external_project/CMakeLists.txt) as an example of using OZO as an external project. I don't know much about your project, but you may try to use it as a submodule. It looks like this is the simplest way until you decide to distribute your project with a package manager.

**Comment by systocrat** [comment]
I managed to figure it out, more or less doing what you suggested.
Thanks!
